# Generated by Django 4.2 on 2023-04-24 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
            },
        ),
        migrations.AddField(
            model_name='personal',
            name='tipo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='pos.tipo'),
            preserve_default=False,
        ),
    ]
